### PR TITLE
Add carthage support

### PR DESCRIPTION
**Pull request by istx25**
because it's awesome :smile:

### CODE REVIEW

**Comment by andreamazz** [comment]
Ok, I made some changes, can you check if it's still working? :)  
Thanks!

**Comment by istx25** [comment]
:disappointed: I just made a test project and when I run `carthage update` I get the following error:

```
douglas $ carthage update
*** Fetching BubbleTransition
*** Checking out BubbleTransition at "bde36fbc4fe94569fd0445a6e223d9d6ab8b1598"
*** xcodebuild output can be found in /var/folders/yt/rwfqhzn90gj7xvm2gkhx4c780000gn/T/carthage-xcodebuild.MUPyoL.log
*** Building scheme "BubbleTransition" in BubbleTransition.xcodeproj
2015-05-29 01:12:27.038 xcodebuild[46730:3241089] [MT] PluginLoading: Required plug-in compatibility UUID 9F75337B-21B4-4ADC-B558-F9CADF7073A7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Alcatraz.xcplugin' not present in DVTPlugInCompatibilityUUIDs
** BUILD FAILED **


The following build commands failed:
    ProcessInfoPlistFile /Users/douglas/Library/Developer/Xcode/DerivedData/BubbleTransition-hbvblounmklatyffrumxuooemfax/Build/Products/Release-iphonesimulator/BubbleTransitionTests.xctest/Info.plist BubbleTransitionTests/Info.plist
(1 failure)
```

Checkout my test project: https://www.dropbox.com/s/dl3h986j064flwl/BubbleTransition-Test.zip?dl=0

**Comment by istx25** [comment]
I've only recently started using CocoaTouch Frameworks so don't quote me, but I'm pretty sure the source files need to be included in `/BubbleTransition` to be included in the build export. :confused:

**Comment by andreamazz** [comment]
Alamofire does the same and it works. As long as the files are referenced in the project, even if they are not phisicaly in a subfolder, it should be ok

**Comment by istx25** [comment]
Oh cool.

**Comment by andreamazz** [comment]
Ok, got it, my bad, I forgot to remove the unused test target.

**Comment by istx25** [comment]
Yeah, I saw that in there just now too.

**Comment by andreamazz** [comment]
Ok, I can confirm that it's working.

**Comment by istx25** [comment]
Sweet. Let me check as well

**Comment by istx25** [comment]
Works for me!

**Comment by istx25** [comment]
I think a new release is necessary so we can clone from that instead of master.

**Pull request merged**
