### PR TITLE
Swift 2.0 compatibility

### PR DESCRIPTION
**Pull request by Deub27**
Hi, 
Here is a Swift2.0 compatibility (XCode7 beta5).

I suggest to create a branch swift-2.0

### CODE REVIEW

**Comment by andreamazz** [comment]
Hi @Deub27, thanks for the PR. 
Instead of force unwrapping `containerView` it would be best to use a `guard` statement and return immediately if the view is nil. Could you update your commit?

**Comment by Deub27** [comment]
Hi, thanks for your advice.
I just committed an update.

**Comment by andreamazz** [comment]
Ace :+1:

**Comment by andreamazz** [comment]
Merged in the branch `swift-2`  
Will move to master with the GM of Xcode 7.

**Pull request closed without merging**
